-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Sep 08, 2017 at 10:26 AM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project`
--

-- --------------------------------------------------------

--
-- Table structure for table `project`
--

CREATE TABLE `project` (
  `SNO` int(100) NOT NULL,
  `CATEGORY` varchar(100) NOT NULL,
  `SUBCATEGORY` varchar(100) NOT NULL,
  `DESCP` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `project`
--

INSERT INTO `project` (`SNO`, `CATEGORY`, `SUBCATEGORY`, `DESCP`) VALUES
(1, 'Artificial Intelligence Research Projects', 'Automated Planning & Control', 'Automated Planning and Control study the computational process of generating a plan, a course of action for an agent to execute towards achieving its goal or objective. Historically, planning and control communities have respectively focused on discrete and continuous state/action spaces, though this difference is reducing slowly. The planning group at the University of Washington has been active in the development of planning algorithms and representations since 1990. This historical website lists the earlier projects, publications, and download links. '),
(2, 'Artificial Intelligence Research Projects', 'Robotics', 'Human-robot interactionRobotics researchers at UW CSE are engaged in ground-breaking work in mechanism design, sensors, computer vision, robot learning, Bayesian state estimation, control theory, numerical optimization, biomechanics, neural control of movement, computational neuroscience, brain-machine interfaces, natural language instruction, and physics-based animation. We are currently working to define large-scale joint initiatives that will enable us to leverage our multi-disciplinary expertise to attack the most challenging problems in field.\r\n'),
(3, 'Artificial Intelligence Research Projects', 'Brain-Computer Interfaces & Computational Neuroscience', 'In 2006, our group became one of the first to demonstrate the control of a humanoid robot using a non-invasive brain computer interface (BCI). The system consists of a robot, an electrode cap for sensing brainwaves, and a graphical user interface for controlling the robot remotely. Our original research demonstrated that the BCI can be used to command a HOAP-2 humanoid robot to select and fetch desired objects from remote locations. We have more recently proposed a framework for adaptive hierarchical brain-computer interfacing that allows the user to teach a robot new behaviors on-the-fly. '),
(4, 'Artificial Intelligence Research Projects', 'Machine Learning', 'UW is one of the world''s top centers of research in machine learning. We are active in most major areas of ML and in a variety of applications like natural language processing, vision, computational biology, the Web, and social networks. Check out the links on the left to find out who''s who and what''s happening in ML at UW.   '),
(5, 'Artificial Intelligence Research Projects', 'Natural Language Processing', 'Studies a range of core NLP problems (such as parsing, information extraction, and machine translation) as well as emerging challenges (such as modeling and processing social media text, analyzing linguistic style, and jointly modeling language and vision).'),
(6, 'Artificial Intelligence Research Projects', 'Computational Biology', 'Developing machine learning algorithms that will enable the use of an individual’s comprehensive biological information to predict or diagnose diseases, and to find or develop the best therapy for that individual.The aim of our research is to resolve this challenge by developing machine learning algorithms that jointly model sophisticated interactions among many variables such as genetic variation, genes, pathways and disease, and robustly learn from vast amounts of data in order to better understand and treat disease. An approach that can robustly infer the pathways that can define disease processes will dramatically improve our understanding of diseases and advance personalized medicine in its treatment. We aim to realize this goal by using modern, advanced machine learning techniques.'),
(7, 'COMPUTER SIMULATION', 'Web cache simulation', 'A popular idea in Internet research is a caching web server, a program that will preload a cache with web pages that have been accessed in the recent past. This way, when you wish to access the page you do so directly from you machine and do not need to go across the network. Build a simulation of this to see if it improves (1) the users perceived performance and (2) the network performance.'),
(8, 'COMPUTER SIMULATION', 'Stock price / performance system', 'Quite a bit of time and effort is spent estimating whether the price of a stock will go up or down, and when it will change from going up to going down, or vice versa. The are a number of resources on the net with historical stock price information. Use some data as input to a simulation model to predict the future price of a stock.'),
(9, 'COMPUTER SIMULATION', 'Ambulance simulation system', 'A continuing debate is where to keep emergency vehicles such as ambulances. Build a simulation system and test whether it is best to keep ambulances (1) at hospitals, (2) fire stations, (3) close to the interstate.\r\n'),
(10, 'COMPUTER SIMULATION', 'A tax simulation system', ' Another continuing debate is whether to increase taxes. By increasing taxes we mean increasing the tax rate. The question is whether this will raise revenue or decrease revenue (the actual number of tax dollars collected). There are a number of possibilities (1) increasing business income tax vs. businesses moving, (2) increasing personal income tax vs. people moving, (3) creating an internet sales tax. In each of these cases your model probably needs to consider the proportion of local to national businesses and the proportion of people willing to move locally or move nationally for a job.\r\n'),
(11, 'COMPUTER SIMULATION', 'Airline system simulation', 'Build yourself a small airline, run simulations to minimize the cost of operations and to maximize revenue. To maximize revenue you want to fill as many seats on an airplane as possible. To minimize expenses airplanes should fly to the service center(s) loaded with passengers.'),
(12, 'COMPUTER SIMULATION', 'Simulate a busy restaurant''s seating policy', 'Assume that the restaurant does not take reservations (although adding reservations to the simulation might be interesting). When customers arrive, they check in at the main podium and give their name, number of people in the party, and smoking preference. Some will go to the bar and may or may not choose to eat there instead of waiting for a table. Others will simply sit in benches, waiting for their party to be called. When a party is seated, they should have some random eating time (or you might want to simulate the eating process in more detail -- ordering, salad, entree, dessert, etc.) before leaving. Tables and seats in the bar would be resources here. What if a party of 20 shows up? Can some tables (resources) be pushed together to accommodate large parties?'),
(13, 'DATABASE SYSTEM', 'INVENTORY CONTROL MANAGEMENT DATABASE PROJECT', 'Design goals: maintain a proper variety of required items, increase inventory turnover, reduce and maintain optimize inventory and safety stock levels, obtain low raw material prices, reduce storage cost, reduce insurance cost, reduce taxes'),
(14, 'DATABASE SYSTEM', 'STUDENT RECORD KEEPING SYSTEM DATABASE PROJECT', 'Design goals: a student file that contains the information about student, a stream file, a marks file, a fee file, concession/scholarship etc. You can check simple version of this project  Student Database Management System in C++'),
(15, 'DATABASE SYSTEM', 'ONLINE RETAIL APPLICATION DATABASE PROJECT', 'A customer can register to purchase an item. The customer will provide bank account number and bank name (can have multiple account number). After registration, each customer will have a unique customerid, userid and password. A customer can purchase one or more item in different quantities. The items can of different classes based on their prices. Based on the quantity, the price of the item and discount (if any) on the purchased items, the bill will be generated. A bank account is required to settle the bill. The items can be ordered to one or more suppliers'),
(16, 'DATABASE SYSTEM', 'COLLEGE DATABASE DATABASE PROJECT', 'A college contains many departments. Each department can offer any number of courses. Many instructors can work in a department, but an instructor can work only in one department. For each department, there is a head, and an instructor can be head of only one department. Each instructor can take any number of courses, and a course can be taken by only one instructor. A student can enroll for any number of courses and each course can have any number of students.'),
(17, 'DATABASE SYSTEM', 'RAILWAY SYSTEM DATABASE PROJECT', 'A railway system, which needs to model the following:\r\n\r\n\r\n Stations\r\n Tracks, connecting stations. You can assume for simplicity that only one track exists between any two stations. All the tracks put together to form a graph.\r\n Trains, with an ID and a name\r\n Train schedules recording what time a train passes through each station on its route. \r\nYou can assume for simplicity that each train reaches its destination on the same day and that every train runs every day. Also for simplicity, assume that for each train, for each station on its route,  you store\r\n\r\n\r\n Time in, \r\n Timeout (same as time in if it does not stop)\r\n A sequence number so the stations in the route of a train can be ordered by sequence number.\r\n Passenger booking consisting of train, date, from-station, to station, coach, seat and passenger name.\r\n'),
(18, 'DATABASE SYSTEM', 'HOSPITAL MANAGEMENT SYSTEM DATABASE PROJECT', 'A patient will have unique Patient ID.  Full description about the patient about personal detail and phone number, and then Disease and what treatment is going on. The doctor will handle patients, One doctor can Treat more than 1 patient. Also, each doctor will have unique ID. Doctor and Patients will be related. Patients can be admitted to hospital. So different room numbers will be there, also rooms for Operation Theaters and ICU.  There are some nurses, and ward boys for the maintenance of hospital and for patient take care.  Based upon the number of days and treatment bill will be generated.\r\n'),
(19, 'Embedded Systems', 'Password Based Door Lock System using 8051 Microcontroller', 'This system demonstrates a password based door lock system wherein once the correct code or password is entered, the door is opened and the concerned person is allowed access to the secured area. After some time, the door would be closed. Read this post completely to get more information.'),
(20, 'Embedded Systems', 'Human Detection Robot', 'Here is an IR Sensor based human detection robot designed using 8051 microcontroller. It is mainly used to save the people in accidents and explosions, to find the enemies, etc.\r\n'),
(21, 'Embedded Systems', 'GSM Controlled Robot using Microcontroller', 'This is an SMS controlled robot designed using 8051 Microcontroller and is used to control the robot directions like forward, backward, left and right by sending SMS from the mobile.'),
(22, 'Embedded Systems', 'Password based Circuit Breaker', 'This is an SMS controlled robot designed using 8051 Microcontroller and is used to control the robot directions like forward, backward, left and right by sending SMS from the mobile.'),
(23, 'Embedded Systems', 'Fingerprint based Biometric Attendance System', 'This biometric attendance system circuit is designed using AVR Microcontroller. It helps to take the attendance in educational institutions, industries, etc.\r\n'),
(24, 'Embedded Systems', 'Digital Temperature Sensor', 'The main principle of this circuit is to display the digital temperature value. These are mainly used in environmental applications.'),
(25, 'Networking Projects', 'Network Desktop Manager Java Project', 'Network is to connect two or more computers together with the ability to communicate with each other. Networking is to link two or more computing devices together for the purpose of sharing data. It provides design, programming, development and operational support for LANs, WANs and other networks.'),
(26, 'Networking Projects', 'Computer Network Project', 'The purpose of this Computer Network-Project is to implement a simplified web system. The system consists of three programs, the DNS server program, the Web server program, and the client program. The client program consists of two parts, a browser simulator and a client program for system testing.'),
(27, 'Networking Projects', 'IP Recovery Using Multiple Routing Configurations Networking Project Report', 'Introduction to IP Recovery Using Multiple Routing Configurations Networking Project: With the invention of internet the communication system is being developed to a great extent. Presently slow junction of routing protocols for a network infrastructure is a great problem faced by numerous people, so to recuperate the failures of IP networks.'),
(28, 'Networking Projects', 'Network Administration Tool Final Year Project Report\r\n', 'Introduction to Network Administration Tool Project: Administrators have the most important tasks, and this is why to make their jobs easy, network administrative tool has been introduced, which is a software package. It is with the help of this tool, the administrator will be able to gain a full control of the software.'),
(29, 'Networking Projects', 'CSE Project for B.tech on Network Administrator Tool with Project Report\r\n', 'Introduction to Network Administrator Tool with Project: The network administrator tool has been developed in order to provide remote service to all the clients of the administrator that belong to the same network. This tool has the ability to act as a network administrator to all the clients and can provide services remotely like remote log'),
(30, 'Networking Projects', 'CSE Mini Networking Project on Prevention of Congestion Collapse\r\n', 'Introduction to Networking Project on Prevention of Congestion Collapse: One of the most important things that is to be kept in mind while dealing with the virtual world is that, every service, protocol and algorithm that is introduced in the internet must essentially scale well. This is usually termed as a scalability argument.'),
(31, 'Information Security', 'Cluster-Based Boosting', 'Boosting is an iterative method that improves the predictive accuracy for supervised (machine) learning algorithms. Boosting operates by learning multiple functions with subsequent functions that specialize in incorrect instances where the previous functions predicted the wrong label. Despite considerable success, boosting still has difficulty on knowledge sets with bound varieties of problematic training data (e.g., label noise) and when advanced functions overfit the training knowledge. We propose a completely unique cluster-based boosting (CBB) approach to address limitations in boosting for supervised learning systems.'),
(32, 'Information Security', 'Genetic Algorithm-Based Moving Object Detection for Real-time Traffic Surveillance', 'Recent developments in vision systems like distributed smart cameras have encouraged researchers to develop advanced laptop vision applications suitable to embedded platforms. In the embedded surveillance system, where memory and computing resources are restricted, easy and economical laptop vision algorithms are needed. During this letter, we tend to present a moving object detection technique for real-time traffic surveillance applications. The proposed methodology may be a combination of a genetic dynamic saliency map (GDSM), which is an improved version of dynamic saliency map (DSM) and background subtraction. The experimental results show the effectiveness of the proposed methodology in detecting moving objects.'),
(33, 'Information Security', 'Modeling and Verification of Online Shopping Business Processes by Considering Malicious Behavior ', 'Recently, on-line looking integrating third-party payment platforms (TPPs) introduces new security challenges because of complex interactions between Application Programming Interfaces (APIs) of Merchants and TPPs. Malicious purchasers might exploit security vulnerabilities by calling APIs in an arbitrary order or enjoying various roles. To deal with the security issue in the first stages of system development, this paper presents a formal methodology for modeling and verification of online searching business processes with malicious behavior patterns considered based mostly on Petri nets. We tend to propose a formal model known as E-commerce Business Method Net to model a normal on-line searching business process that represent supposed functions, and malicious behavior patterns representing a possible attack that violates the security goals at the need analysis section.'),
(34, 'Information Security', 'Bio-inspired image enhancement derived from a ''rank order coding’ model', 'In this study, the authors propose a brand new methodology to reinforce image data, based on wavelet decomposition and original partial reconstruction of image. This reconstruction called ''asynchronous reconstruction'' isn''t carried out in the identical manner as the standard sequential one. It''s based mostly on rank order coding. Of course, while sequential reconstruction is to add all or a part of the responses obtained for each scale of ''coarse to fine'' decomposition, asynchronous reconstruction tries to be nearer to human brain that uses a limited variety of frequency channels. Actually, when wavelet decomposition, responses are sorted from high down for every pixel of the image. Final asynchronous reconstruction for each pixel is obtained by adding a chosen range of wavelet responses, beginning by the most response.'),
(35, 'Information Security', '5G radio access architecture and technology [Industry Perspectives]', 'In early 2012, the International Telecommunication Union (ITU) under the United Nations initiated a program to develop an International Mobile Telecommunication (IMT) system for 2020 and beyond (IMT-2020), thereby officially coming out the global race toward a however to be outlined fifth generation (5G) mobile network. Quick forward three years, the vision of this next-generation system is beginning to require form. A recent ITU-Radiocommunication Standardization Sector (ITU-R) Draft Recommendation [one] on IMT-2020 identifies 3 key usage eventualities in 5G as enhanced mobile broadband, huge machine-sort communications, and ultra-reliable and low-latency communications. The identical report additionally problems steerage on the wants for these eventualities in terms of performance index such as spectrum potency, latency, association density, and space traffic capacity, as shown in Fig. 1.'),
(36, 'Information Security', 'Visually Exploring Transportation Schedules', 'Public transportation schedules are designed by agencies to optimize service quality under multiple constraints. However, real service sometimes deviates from the set up. Thus, transportation analysts need to identify, compare and explain both eventual and systemic performance problems that has got to be addressed therefore that better timetables will be created. The purely statistical tools commonly utilized by analysts cause several difficulties thanks to the big variety of attributes at trip- and station-level for planned and real service. Additionally challenging is the requirement for models at multiple scales to go looking for patterns at completely different times and stations, since analysts don''t recognize specifically where or when relevant patterns may emerge and would like to compute statistical summaries for multiple attributes at different granularities.'),
(37, 'Embedded systems based IEEE projects', 'Prepaid Energy Meter with GSM Interface', 'The main intention of this project is to make energy billing prepaid. It is a multipurpose system that integrates all the functions with a prepaid billing arrangement and automatic message sending fature.  This B. Tech projects is very useful to the power sector industries to effectively record the units consumed for billing purposes and also monitor several other factors to reduce power thefts. This system developed using 8051 microcontroller and GSM modem. This is one of the best b tech final year projects for ece and eee engineering students.'),
(38, 'Embedded systems based IEEE projects', 'Wireless Power Driven Car or Train', 'This project is a very interesting robotics project in which the robot operated by wirelessly. This project is developed based on this concept to transfer power to a robotic vehicle or electric train or electric car wirelessly. Here, develop a robotic vehicle that operates wireless to run it in a specified path by inductive resonance coupling from the ground level fixed coil developing  a 40 KHz power  from the mains AC source 230Hz. This project is one of the good B.Tech projects in final year projects for eee engineering students.'),
(39, 'Embedded systems based IEEE projects', 'EVM Electronic Voting Machine using PIC Microcontroller', 'An electronic voting machine is an extraordinary electronic project that is used for voting at polling stations. This project provides a push-button switch for different contestants.  A powerful embedded c programming is written in assembly language. This program is burnt onto the PIC 16f series microcontroller to accept votes and to keep counting the total votes polling on it.'),
(40, 'Embedded systems based IEEE projects', 'Solar Inverter by Edgefxkits.com', 'This project is designed to convert the solar energy (DC) to alternating current (AC) for operating the household applications.  The solar panel converts the sun’s energy to DC power using PV cells that is sent to the solar inverter. The solar inverter converts the direct current to alternate current for use in your home electrical loads. In this project the solar energy stored in the batteries. This is wonderful solar projects in electronics for ece and eee engineering students to buy in edgefxkits.com'),
(41, 'Embedded systems based IEEE projects', 'PC Mouse Operated Electrical Load Control with VB Application', '\r\nThis project is designed to control electrical by a personal computer. It is very help full for the industries wherein the lights are controlled by PC for better management. The proposed system integrated with electrical loads and also connected to the PC. The “DAQ” software is loaded in the  PC which presents the on/off buttons. By using on/off buttons to control electrical loads in the home based on relays. This is a very interesting project for ece and eee engineering students as you can do mini projects or main project.'),
(42, 'Embedded systems based IEEE projects', 'Arduino based Underground Cable Fault Detection', 'The underground cable system is a common in many urban areas which is followed by many kilometers wherein any fault occurs for some reason, at that time the repairing process related to that particular cable is difficult to not knowing the exact location of the cable fault. The proposed system is designed to determine the distance of underground cable fault from the base station in kilometers through an Arduino development board. This is very interesting B. Tech project for ece and eee students.'),
(43, 'Neural Network', 'Individual Stress Diagnosis From Skin Conductance Sensor Signals ', 'Human stress has become a serious problem affecting people’s life. The current state of sensor technology allows developing systems measuring physical symptoms reflecting people’s stress level. However, the detection of stressful events using the skin conductance (SC) and finger temperature (FT) data is a challenging task due to varieties of patterns in the data. Also each person handles stress in a different way.\r\n\r\nA big part of the thesis work is to compare the proximity of the results from FT sensor and SC sensor data using two artificial intelligence techniques (AI): neural networks (NN) and case base reasoning (CBR).'),
(44, 'Neural Network', 'SMARTEYE – Vehicle Security System Using Facial Recognition ', 'Facial recognition has gained increasing interest in the recent decade. Over the years there have been several techniques being developed to achieve high success rate of accuracy in the identification and verification of individuals for authentication in security systems.\r\n\r\nThis project experiments the concept of combining of multilevel wavelet decomposition transformation and neural network for facial recognition in a specific application with its own limitations, in that of vehicle security access control system. The approach of this project is to conceptualise by simulation of the various processes involved in developing an implementable system.'),
(45, 'Neural Network', 'State-Clustering Based Multiple Deep Neural Networks Modeling Approach for Speech Recognition', 'The hybrid deep neural network (DNN) and hidden Markov model (HMM) has recently achieved dramatic performance gains in automatic speech recognition (ASR). The DNN-based acoustic model is very powerful but its learning process is extremely time-consuming. In this paper, we propose a novel DNN-based acoustic modeling framework for speech recognition, where the posterior probabilities of HMM states are computed from multiple DNNs (mDNN), instead of a single large DNN, for the purpose of parallel training towards faster turnaround. In the proposed mDNN method all tied HMM states are first grouped into several disjoint clusters based on data-driven methods.'),
(46, 'Neural Network', 'An Enhanced Fuzzy Min–Max Neural Network for Pattern Classification', 'An enhanced fuzzy min-max (EFMM) network is proposed for pattern classification in this paper. The aim is to overcome a number of limitations of the original fuzzy min-max (FMM) network and improve its classification performance. The key contributions are three heuristic rules to enhance the learning algorithm of FMM. First, a new hyperbox expansion rule to eliminate the overlapping problem during the hyperbox expansion process is suggested. Second, the existing hyperbox overlap test rule is extended to discover other possible overlapping cases. Third, a new hyperbox contraction rule to resolve possible overlapping cases is provided. Efficacy of EFMM is evaluated using benchmark data sets and a real medical diagnosis task.'),
(47, 'Neural Networks', 'Cryptography using Artificial Neural Networks', 'A Neural Network is a machine that is designed to model the way in which the brain performs a task or function of interest. It has the ability to perform complex computations with ease. The objective of this project was to investigate the use of ANNs in various kinds of digital circuits as well as in the field of Cryptography.\r\n\r\nDuring our project, we have studied different neural network architectures and training algorithms. A comparative study is done between different neural network architectures for an Adder and their merits/demerits are discussed. Using a Jordan (Recurrent network), trained by back-propagation algorithm, a finite state sequential machine was successfully implemented.'),
(48, 'Neural Networks', 'Sensor Less Control of Induction Machines, in Railway Applications ', 'In this project, a sensor-less system has been developed for an induction machine in railway applications. The approach which was taken in this project thesis is a consequence of the expectations of the company: investigate the possibilities of having the current generation of Alstom’s drive system working without use of a speed sensor. Some tests have thus been performed in order to validate parts of this statement.\n\nHowever, because of the substantial time that would require an exhaustive investigation and a complete development, from simulation to tests on a real train, it has been decided to focus more on selecting a method relevant for Alstom’s specications, and simulate it in order to identify issues.'),
(49, 'Android', 'Secure Digi Locker Application', 'Secured Digi Locker is an advanced application in which the file storing makes it very efficient and reliable as we don’t have to carry each and every document with us every time. Legal document such as Passport, Birth Certificate etc. are very important and it can be misused. Uploading it to any server is a risk taking action as it can be hacked and keep it in our phone is also dangerous. Therefore, we have developed a system that saves the uploaded document in an encrypted form and stores it in the Internal Memory, to avoid any kind of hacking internal or external. The main advantage of this system is that it asks for Secure Pin to access the file which we enter while registering ourselves. Secure pin ensures that if our phone is in someone’s hand they won’t be able to access the files. The files are secured in many ways which no intruder can access them in any case. We make uses of SQLite as it’s backend to support the application.'),
(50, 'Android', 'Mobile Based Attendance System', 'The mobile attendance system has been built to eliminate the time and effort wasted in taking attendances in schools and colleges. It also greatly reduces the amount of paper resources needed in attendance data management.This is an android mobile app. It’s built to be used for school/college faculty so that they may take student attendance on their phones.'),
(51, 'Android', 'Android Antenna Positioning System', 'This Android Based Antenna Positioning System is very innovative system as it helps to position the antenna with the help of android application. This helps the antenna to point straight towards the sending signal device so as to capture the signal. For this the system uses 8051 family microcontroller and LCD screen. This LCD screen is used to display the status of the angle of the antenna. The system makes use of stepper motor to demonstrate as the antenna motor which is used to move the antenna in proper direction. Antenna is moved by the user commands received through the android application. This user commands are then received by the bluetooth receiver modem. As the system receives user commands, it moves the antenna on the basis of input parameters provided.'),
(52, 'Android', 'Voice Controlled Robotic Vehicle', 'This project Voice Controlled Robotic Vehicle helps to control robot through voice commands received via android application. The integration of control unit with Bluetooth device is done to capture and read the voice commands. The robotic vehicle then operates as per the command received via android application. For this 8051 microcontroller is integrated in the system which makes it possible to operate the vehicle via android application.\r\nThe controlling device may be any android based Smartphone/tab etc having an android OS. The android controlling system provides a good interactive GUI that makes it easy for the user to control the vehicle. The transmitter uses an android application required for transmitting the data.'),
(53, 'Matlab Based Projects', 'Signature Verification System', 'Here we proposed a system where we normalize the signature image and system checks whether the signature matches with original signature. System applies image pre-processing steps. Image is converted to black and white image. Morphing technology is used in order to thin the image. By extracting black pixels, the curve of the signature is recognized. X and Y co-ordinates of original image is extracted. New co-ordinates are generated and signature is rotated by passing the new co-ordinates. After rotating the image, Signature might go out of the boundary therefore we calculated the moving co-ordinates of x and y. Finally, the image is cropped. This cropped image is compared with the theta value which is calculated during curve calculation. System checks whether the theta value is matched. '),
(54, 'Matlab Based Projects', 'Symbol Recognition Using Matlab', 'We here proposed a system where symbol are recognized by the system, user will input symbol images system will apply algorithm to identify the symbol. Here in this system we applied some image processing steps in order to work with images. We converted the rgb image into gray scale image. Image is converted into gray scale image to apply further image processing steps. Than gray scale image into black white image, this is done due to accuracy. We had applied some image preprocessing steps in order to remove some unwanted objects and environmental interference. Here we store symbol templates in one directory each image will be of fixed size so that it would be easier to recognize correct symbol. These template images will be in black and white form. System will create dataset of these templates.'),
(55, 'Matlab Based Projects', 'Bone Fracture Detection System', 'Here we proposed an automated techniques and methods to detect fracture. X-ray images are examined manually but it is time consuming and prone to errors. As X-ray images are more suspected to noise we used many preprocessing steps to remove noise and blur from image. Thus, system is able to detect fracture more accurately. System detects fracture based on the type of fracture. Noise is removed from the image and image is transformed to clearer image so that system can easily detect fracture. We used image processing methodology to track bone. All unwanted as well as smaller objects are removed by the system. Finally based on the connected component, system detects fracture. '),
(56, 'Matlab Based Projects', 'Brain Tumor Detection Using Image Segmentation', 'Brain tumor at early stage is very difficult task for doctors to identify. MRI images are more prone to noise and other environmental interference. So it becomes difficult for doctors to identify tumor and their causes. So here we come up with the system, where system will detect brain tumor from images. Here we convert image into grayscale image. We apply filter to image to remove noise and other environmental interference from image. User has to select the image. System will process the image by applying image processing steps. We applied a unique algorithm to detect tumor from brain image. But edges of the image are not sharp in early stage of brain tumor.'),
(57, 'Matlab Based Projects', 'Image Retrieval Using Feature Extraction', 'Here we proposed a system where similar images are fetched based on image features. As images are more suspected to noise we used many preprocessing steps to remove noise . Image features are extracted using feature extraction method and these features are stored into database. Query image feature values are compared with other images in directory and similar image is extracted and displayed to user. Image is quantized in hsv color space into equal bins and the features extracted from hsv color. Filter is used to remove noise from image. Image is given as an input to the application, system find its nearest neighbor from the training set and system fetches nearest image to the input test image.'),
(58, 'Matlab Based Projects', 'Watermark Images Using Discrete Cosine Transform', 'Here we proposed a system where you can hide message image into RGB image. Here we used digital watermarking for embedding. Digital watermarking is a technology for embedding various types of information in digital content. A digital watermark is digital signal or pattern inserted into digital content. We had used Discrete Cosine Transform (DCT) for lossy compression of images. Watermarking technique has recently developed for image watermarking and it can be used to embed the information into image and can be efficiently extract back the information. In this system we will hide black and white image under RGB Image and extracts back the black and white image from RGB image. To apply watermarking we must resize the image for further processing. Watermark value will be replaced in block. Finally, system will output original image after removing watermark from image.'),
(59, 'Informational Technology', 'Mobile Ticket Reservation System', 'As the reach of mobile expanding , it started to do magical things. For instance, if you are in a new city and want to watch movie or catch a bus, but you do not have time to purchase a ticket? What would you do 10 years back? Nothing. Now, with mobile in hand and software such as mobile ticket reservation system you can book your ticket from anywhere.\r\nosTicket is a open source support ticket system. It seamlessly integrates inquiries created via email, phone and web-based forms into a simple easy-to-use multi-user web interface.'),
(60, 'Informational Technology', 'Human Resource Management System', 'You have studied many types of management systems , one of the most important among those is Human Resource Management. This system can be used in any organization or institute. The unique thing about this project is its usefulness in real market. You can develop this project for sale purposes also.\r\n\r\nMost of these systems are offline software, if you can develop this system online with rich features, you will have good chance of success in market.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `project`
--
ALTER TABLE `project`
  ADD PRIMARY KEY (`SNO`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `project`
--
ALTER TABLE `project`
  MODIFY `SNO` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
